# Generated by Django 4.1.6 on 2023-04-27 21:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.CharField(max_length=10)),
                (
                    "car_speed",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "car_rpm",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(9.0),
                        ],
                    ),
                ),
                ("car_distance", models.PositiveIntegerField(default=0)),
                ("car_run_time", models.CharField(max_length=10)),
                ("car_tempreture", models.CharField(max_length=4)),
                (
                    "car_engine_load",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Car",
            },
        ),
        migrations.CreateModel(
            name="MCVUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="mcv_user/")),
                ("mobile", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "MCV USER",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="mcv_user/")),
                ("mobile", models.CharField(max_length=20)),
                (
                    "driver_action",
                    models.CharField(
                        choices=[
                            ("Driving safe", "Driving safe"),
                            ("Texting right", "Texting right"),
                            ("Talk with right", "Talk with right"),
                            ("Texting left", "Texting left"),
                            ("Talk with left", "Talk with left"),
                            ("Turn on radio", "Turn on radio"),
                            ("Drinking", "Drinking"),
                            ("look behind", "look behind"),
                            ("hair and makeup", "hair and makeup"),
                            ("talking passenger", "talking passenger"),
                        ],
                        default="Driving safe",
                        max_length=100,
                    ),
                ),
                (
                    "drive_car",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mcv_app.car",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Driver",
            },
        ),
        migrations.CreateModel(
            name="Car_Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic_sarial", models.CharField(max_length=7)),
                ("diagnostic_error_type", models.TextField()),
                (
                    "diagnostic_for_car",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mcv_app.car",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Car Diagnostic",
            },
        ),
    ]
