# Generated by Django 4.1.6 on 2023-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcv_app", "0003_alter_car_diagnostic_diagnostic_for_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="Latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="Longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mcvuser",
            name="Latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mcvuser",
            name="Longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
